# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [3]:
### [your code here]
print(np.__version__)

2.2.3


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [4]:
### [your code here]
a = np.random.rand(2, 3, 5)


### 4. Print a.


In [5]:
### [your code here]
print(a)

[[[0.75112076 0.61603698 0.19275811 0.48494392 0.70056367]
  [0.84530822 0.37925221 0.6466139  0.18504684 0.41250388]
  [0.41347344 0.36909174 0.59766105 0.93610897 0.34683226]]

 [[0.00611902 0.40714761 0.34294399 0.34605308 0.3541567 ]
  [0.30543402 0.53761386 0.04022691 0.47663292 0.39659743]
  [0.23376935 0.24420374 0.73267942 0.36567457 0.65028326]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [10]:
### [your code here]
b = np.ones((5,2,3), dtype=int)


### 6. Print b.


In [11]:
### [your code here]
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [9]:
### [your code here]
print(a.size) == print(b.size)

30
30


True


### 8. Are you able to add a and b? Why or why not?


In [ ]:
### [your code here]
a + b
# I can't, because they have different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [17]:
### [your code here]
c = np.transpose(b, (1,2,0))

In [18]:
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [19]:
### [your code here]
d = a + c

In [20]:
print(d)

[[[1.75112076 1.61603698 1.19275811 1.48494392 1.70056367]
  [1.84530822 1.37925221 1.6466139  1.18504684 1.41250388]
  [1.41347344 1.36909174 1.59766105 1.93610897 1.34683226]]

 [[1.00611902 1.40714761 1.34294399 1.34605308 1.3541567 ]
  [1.30543402 1.53761386 1.04022691 1.47663292 1.39659743]
  [1.23376935 1.24420374 1.73267942 1.36567457 1.65028326]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [21]:
### [your code here]

print(a)

[[[0.75112076 0.61603698 0.19275811 0.48494392 0.70056367]
  [0.84530822 0.37925221 0.6466139  0.18504684 0.41250388]
  [0.41347344 0.36909174 0.59766105 0.93610897 0.34683226]]

 [[0.00611902 0.40714761 0.34294399 0.34605308 0.3541567 ]
  [0.30543402 0.53761386 0.04022691 0.47663292 0.39659743]
  [0.23376935 0.24420374 0.73267942 0.36567457 0.65028326]]]


In [23]:
print(d)

[[[1.75112076 1.61603698 1.19275811 1.48494392 1.70056367]
  [1.84530822 1.37925221 1.6466139  1.18504684 1.41250388]
  [1.41347344 1.36909174 1.59766105 1.93610897 1.34683226]]

 [[1.00611902 1.40714761 1.34294399 1.34605308 1.3541567 ]
  [1.30543402 1.53761386 1.04022691 1.47663292 1.39659743]
  [1.23376935 1.24420374 1.73267942 1.36567457 1.65028326]]]


In [ ]:
#the're different by 1


### 12. Multiply a and c. Assign the result to e.


In [24]:
### [your code here]
e = a * c



### 13. Does e equal to a? Why or why not?


In [ ]:
### [your code here]
#yes because it multiplied the array a by 1
print(e)

[[[0.75112076 0.61603698 0.19275811 0.48494392 0.70056367]
  [0.84530822 0.37925221 0.6466139  0.18504684 0.41250388]
  [0.41347344 0.36909174 0.59766105 0.93610897 0.34683226]]

 [[0.00611902 0.40714761 0.34294399 0.34605308 0.3541567 ]
  [0.30543402 0.53761386 0.04022691 0.47663292 0.39659743]
  [0.23376935 0.24420374 0.73267942 0.36567457 0.65028326]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [47]:
### [your code here]
d_max = np.max(d)
print(d_max)


1.9361089685173294


In [48]:
d_min = np.min(d)
print(d_min)


1.0061190209427808


In [49]:
d_mean = np.mean(d)
print(d_mean)

1.4438950608716425



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [33]:
### [your code here]
empty_test = np.random.rand(2,3,5)
f = np.empty(empty_test.shape)


In [34]:
print(f)

[[[0.95316349 0.58008014 0.52790872 0.31831299 0.38751482]
  [0.36054044 0.9247196  0.80558938 0.22524435 0.6362994 ]
  [0.20080717 0.93578056 0.23975435 0.8535695  0.19544619]]

 [[0.22699273 0.82248308 0.88940626 0.87737578 0.50219987]
  [0.92140237 0.4856602  0.92448561 0.97643163 0.21382483]
  [0.06604771 0.16092948 0.10170082 0.8008581  0.20918596]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [50]:
### [your code here]
f[(d > d_min) & (d < d_mean)] = 25

In [51]:
f[(d < d_max) & (d > d_mean)] = 75

In [52]:
f[d == d_mean] = 50

In [53]:
f[(d < d_min) ] = 0

In [54]:
f[d == d_max] = 100





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [55]:
### [your code here]
print(d)

[[[1.75112076 1.61603698 1.19275811 1.48494392 1.70056367]
  [1.84530822 1.37925221 1.6466139  1.18504684 1.41250388]
  [1.41347344 1.36909174 1.59766105 1.93610897 1.34683226]]

 [[1.00611902 1.40714761 1.34294399 1.34605308 1.3541567 ]
  [1.30543402 1.53761386 1.04022691 1.47663292 1.39659743]
  [1.23376935 1.24420374 1.73267942 1.36567457 1.65028326]]]


In [56]:
print(f)

[[[ 75.  75.  25.  75.  75.]
  [ 75.  25.  75.  25.  25.]
  [ 25.  25.  75. 100.  25.]]

 [[100.  25.  25.  25.  25.]
  [ 25.  75.  25.  75.  25.]
  [ 25.  25.  75.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [ ]:
### [your code here]

